### ISSUE TITLE
Feedback for "Configure the SuccessFactors OData V2 Receiver Adapter"

### ISSUE THREAD

**Issue by fippu82** [SAP-docs/btp-integration-suite#10]
https://help.sap.com/docs/SAP_INTEGRATION_SUITE/51ab953548be4459bfe8539ecaeee98d/d16dd12c5c5649e99c8939879a77f9c0.html?q=odata%20successfactors#loiod16dd12c5c5649e99c8939879a77f9c0__model-operation

There is a broken link [Customized Operators].

**Comment by DavidMitreski5** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by Karunaharan** [comment]
Thanks for the feedback @fippu82 - We will close the issue as a part of our next regular release cycle.

Regards,
Karuna
