### ISSUE TITLE
Contradicting explanation of Spike Arrest

### ISSUE THREAD

**Issue by s3ku** [SAP-docs/btp-integration-suite#102]
### Issue description

The page information contradicts itself. It says "Do not use Spike Arrest to limit traffic from individual clients."
But the example and the explanation of the example does client identification.

Might be a bad example to violate the statement of "not for individual clients"?

### Feedback Type (Optional)

examples or samples

### Page Title on SAP Help Portal (prefilled)

Spike Arrest

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/PRODUCT_ID/66d066d903c2473f81ec33acfe2ccdb4/bf441dc839034613b059cb508ad610f7.html?state=PRODUCTION&version=Cloud&locale=en-US

**Comment by MelanieCueppers** [comment]
Hi @s3ku, thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by Kakabira** [comment]
Hi @s3ku, Thank you for your feedback. I have updated the example in the following topic: https://help.sap.com/docs/sap-api-management/sap-api-management/spike-arrest?version=Cloud
