### ISSUE TITLE
actual stataus returned by API '/BuildAndDeployStatus(TaskId='%s')' is not the same as desctiped there

### ISSUE THREAD

**Issue by Vector6662** [SAP-docs/btp-integration-suite#104]
### Issue description

Hi team,
the status values listed here in the document is different from the actual return values returned by API endpoint(`/BuildAndDeployStatus`):
```go
fullURL := fmt.Sprintf("%s/BuildAndDeployStatus(TaskId='%s')", c.ApiURL, taskID)
```
for example, returns 'SUCCESS' rather than 'Success', 'DEPLOYING' rather than 'Deploying'. 
What about `Fail_On_License_Error`? also all upper cases like above?

Could you please update the document to avoid misleading?

thanks in advance!

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Build and Deploy Status

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/build-and-deploy-status

**Comment by SrutiSagaram** [comment]
Hi @Vector6662 

Thank you for your feedback. We will check and get back to you.

**Comment by pe-gu** [comment]
Thank you!
