### ISSUE TITLE
Further Linkage to JDBC adapter is missing. 

### ISSUE THREAD

**Issue by svenb0** [SAP-docs/btp-integration-suite#105]
### Issue description

Hi, 
for the JDBC adapters the further linkage to the detailed JDBC Adapter help is missing. Can you please check?
![2024-11-15_13-04-47](https://github.com/user-attachments/assets/c9f3e260-152f-4b2e-8279-9e9aa7ee75ce)

### Feedback Type (Optional)

linking

### Page Title on SAP Help Portal (prefilled)

Connectivity Options

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/connectivity-options?version=CLOUD&q=PostgreSQL

**Comment by MelanieCueppers** [comment]
Hi @svenb0, thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by MelanieCueppers** [comment]
Hi @svenb0, thanks for your valuable contribution! We've corrected the issue now.
