### ISSUE TITLE
ReceiverDeterminationInService is missing

### ISSUE THREAD

**Issue by ottfro1** [SAP-docs/btp-integration-suite#106]
### Issue description

ReceiverDeterminationInService is missing

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Add an SAP Process Orchestration System

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/add-sap-process-orchestration-system#prerequisites

**Comment by MelanieCueppers** [comment]
Hi @ottfro1, thank you for your feedback! We’ll look into it and come back to you if we have any questions.
