### ISSUE TITLE
Integration Assessment link leads to 404

### ISSUE THREAD

**Issue by jklingelhoefer** [SAP-docs/btp-integration-suite#107]
### Issue description

The link behind the text Integration Assessment in table Capabilities is a dead link.

### Feedback Type (Optional)

linking

### Page Title on SAP Help Portal (prefilled)

What is SAP Integration Suite?

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/what-is-sap-integration-suite?locale=en-US&version=CLOUD

**Comment by SrutiSagaram** [comment]
@jklingelhoefer thank you for your feedback. We will check and get back to you.

**Comment by motaroberta** [comment]
Thank you, @jklingelhoefer! The link has been fixed.

**Comment by jklingelhoefer** [comment]
164014
