### ISSUE TITLE
Processing: Read Lock Strategy is missing Done File Expected

### ISSUE THREAD

**Issue by noyens** [SAP-docs/btp-integration-suite#108]
### Issue description

Under the processing table for the FTP Sender adapter, the Read Lock Strategy is missing Done File Expected option.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Configure the FTP Sender Adapter

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/configure-ftp-sender-adapter?locale=&q=FTP+sender

**Comment by SrutiSagaram** [comment]
Hi @noyens
Thank you for the feedback. We will check and get back to you.

**Comment by HarshitaSuryavanshi** [comment]
Hi @noyens 
Thanks for the feedback.
This is updated.
https://help.sap.com/docs/integration-suite/sap-integration-suite/configure-ftp-sender-adapter?version=CLOUD&q=ftp
