### ISSUE TITLE
"Transfer Exchange Properties" option not documented

### ISSUE THREAD

**Issue by mwittrock** [SAP-docs/btp-integration-suite#109]
### Issue description

The "Transfer Exchange Properties" checkbox is not currently documented in the list of configuration options on the "Processing" tab.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Configure the JMS Receiver Adapter

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/configure-jms-receiver-adapter?version=Cloud

**Comment by MelanieCueppers** [comment]
Hi @mwittrock, thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by Subhash3549** [comment]
Issue is fixed.

Please find the update in the below link:
https://help.sap.com/docs/cloud-integration/sap-cloud-integration/configure-jms-receiver-adapter?version=Cloud

Thanks for the feedback.

**Comment by mwittrock** [comment]
Great, thanks a lot.
