### ISSUE TITLE
Feedback for "Configure the Microsoft SharePoint Sender Adapter"

### ISSUE THREAD

**Issue by erkamalp** [SAP-docs/btp-integration-suite#14]
https://help.sap.com/docs/integration-suite/sap-integration-suite/configure-microsoft-sharepoint-sender-adapter

Thanks for this comprehensive adapter. But I think there is a bug for special characters in the Directory field. If there is an "&" character in the Directory, it fails to deploy. No matter using escape characters. If you pass it as a parameter, then it gives an error.
![image](https://github.com/SAP-docs/btp-integration-suite/assets/88819437/4a25312e-8075-4fa6-b241-db8e84a3ebbd)
Thanks,
Kind regards,
Erkam Ozturk

**Comment by DavidMitreski5** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by erkamalp** [comment]
> Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

I was wrong, I've found out the problem. it works fine now. Thanks
