### ISSUE TITLE
Create an API Provider - Documentation Issues

### ISSUE THREAD

**Issue by BlairKSAP** [SAP-docs/btp-integration-suite#15]
### Issue description

There are many grammatical errors in this documentation, and some instructions are incorrect. For example (grammar): "You are navigated to Open Connectors home page." An example of incorrect instructions: "Navigate to SAP BTP Cockpit>Subscriptions>Open Connectors" This path does not exist.

### Feedback Type (Optional)

spelling or grammar

### Page Title on SAP Help Portal (prefilled)

Create an API Provider

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/sap-api-management/sap-api-management/create-api-provider

**Comment by MelanieCueppers** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by Kakabira** [comment]
I have fixed the issues in the topic. The changes are available in the cloud version: 
https://help.sap.com/docs/sap-api-management/sap-api-management/create-api-provider?version=Cloud

**Comment by BlairKSAP** [comment]
Great! Thank you for correcting the errors so quickly.

From: Kasturi ***@***.***>
Date: Wednesday, August 2, 2023 at 4:22 AM
To: SAP-docs/btp-integration-suite ***@***.***>
Cc: Krotenko, Blair ***@***.***>, Author ***@***.***>
Subject: Re: [SAP-docs/btp-integration-suite] Create an API Provider - Documentation Issues (Issue #15)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

I have fixed the issues in the topic. The changes are available in the cloud version:
https://help.sap.com/docs/sap-api-management/sap-api-management/create-api-provider?version=Cloud

**Comment by BlairKSAP** [comment]
https://people.sap.com/blair.krotenko

From: sap-doc-bot[bot] ***@***.***>
Date: Friday, August 4, 2023 at 10:56 AM
To: SAP-docs/btp-integration-suite ***@***.***>
Cc: Krotenko, Blair ***@***.***>, Mention ***@***.***>
Subject: Re: [SAP-docs/btp-integration-suite] Create an API Provider - Documentation Issues (Issue #15)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Thank you for your valuable feedback contribution, @BlairKSAP<https://github.com/BlairKSAP>! So that we can recognize your contribution in SAP Community<https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md>, please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:

https://people.sap.com/your-user-name

Thanks!
