### ISSUE TITLE
Error prevention for space in URL(adress)

### ISSUE THREAD

**Issue by NatTh23** [SAP-docs/btp-integration-suite#17]
### Issue description

Hi
Pls create an error when deploying or even while entering the address in the connection details in case it contains  space

Example positive
https://<API>/GWSAMPLE_BASIC/SalesOrderLineItemSet(SalesOrderID='${property.SalesOrderID}',ItemPosition='${property.ItemPosition}')/ToHeader

Example negative 
https://<API>6eff9cbetrial-trial.integrationsuitetrial-apim.us10.hana.ondemand.com/6eff9cbetrial/v1/GWSAMPLE_BASIC/SalesOrderLineItemSet(SalesOrderID='${property.SalesOrderID}',ItemPosition='${property.ItemPosition }')/ToHeader

--> The space between
'${property.ItemPosition 
&
}')
is deployed and leads to an error. 

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

HTTP Receiver Adapter

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/PRODUCT_ID/368c481cd6954bdfa5d0435479fd4eaf/2da452effb764b3bb28f8e0a2f5bd480.html?state=PRODUCTION&version=Cloud&locale=de

**Comment by Karunaharan** [comment]
Hi @NatTh23 - thanks for the feedback. I'm looking into the issue.

Regards,
Karuna

**Comment by Karunaharan** [comment]
Hi @NatTh23,
This is a corner case where camel cases are used in the address. Nevertheless, we are considering your feedback. The concerned engineering teams are informed about having a validation check. Also, please note that "spaces" are allowed in the address field in certain cases.

Closing the issue now. Thanks for taking the time to pass on the useful feedback.

Regards,
Karuna
