### ISSUE TITLE
Wrong method used in the sample code which leads to errors

### ISSUE THREAD

**Issue by stefanressing** [SAP-docs/btp-integration-suite#18]
### Issue description

The method of the sample code is wrong and it should be

def Message processData(Message message) {

### Feedback Type (Optional)

examples or samples

### Page Title on SAP Help Portal (prefilled)

Parse JSON

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/parse-json

**Comment by AnnikaGonnermann** [comment]
Hey @stefanressing. Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by stefanressing** [comment]
https://people.sap.com/sressing

**Comment by Karunaharan** [comment]
Hi @stefanressing,
Could you please elaborate on what error you face? That should help us.
Why I ask - the name of the method is user-defined and shouldn't be causing issues/errors. You can use any name of your choice and still achieve the outcome.

Closing the issue for now. Feel free to repoen.

Regards,
Karuna

**Comment by stefanressing** [comment]
import com.sap.gateway.ip.core.customdev.util.Message;
import java.util.HashMap;
import groovy.json.JsonSlurper;

def Message parseJsonMessage(Message message) {

The Def Message is wrong it needs to be

import com.sap.gateway.ip.core.customdev.util.Message;
import java.util.HashMap;
import groovy.json.JsonSlurper;

def Message processData(Message message) {

Thank you very much

Stefan Ressing
Chief Cloud Architect, Vice President
SAP BTP Global Center of Excellence
SAP America - Lake Mary, 400 International Pkwy 2nd Fl, Lake Mary, FL 32746, United States

M   +16306992235, ***@***.******@***.***>

Join me online: https://www.linkedin.com/in/stefanresssing/

Please consider the impact on the environment before printing this email.

 [signature_3121905136]

***@***.***
***@***.***
Upcoming PTO: None

From: Karunaharan V ***@***.***>
Date: Thursday, September 14, 2023 at 2:27 PM
To: SAP-docs/btp-integration-suite ***@***.***>
Cc: Ressing, Stefan ***@***.***>, Mention ***@***.***>
Subject: Re: [SAP-docs/btp-integration-suite] Wrong method used in the sample code which leads to errors (Issue #18)

Hi @stefanressing<https://github.com/stefanressing>,
Could you please elaborate on what error you face? That should help us.
Why I ask - the name of the method is user-defined and shouldn't be causing issues/errors. You can use any name of your choice and still achieve the outcome.

Closing the issue for now. Feel free to repoen.

Regards,
Karuna
