### ISSUE TITLE
Link to reference not working

### ISSUE THREAD

**Issue by frankmeertens** [SAP-docs/btp-integration-suite#19]
### Issue description

The reference provided at the bottom of the page is not working.

https://uacp2.hana.ondemand.com/viewer/DRAFT/e63fe47de8f84a68b618ed689af9a28b/Dev/en-US/33cce5a5c3ac4f05bc3091e8327646ea.html

To replicate the issue, go to the `Define Root URL` section of the page. You might have to click on the corresponding button to reveal the content.
At the bottom of the instructions, you will find the following text:

> Watch a video tutorial on how to define the metadata (title, version, description, contact) and the root URL(host, schemes, and basePath) for an API here.

The link provided for here is not working.

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Creating APIs

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/sap-api-management/sap-api-management/creating-apis

**Comment by MelanieCueppers** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by Kakabira** [comment]
I have removed the references to the internal links from this topic and have renamed this topic to API Designer.
