### ISSUE TITLE
Content-Type request headers are not excluded

### ISSUE THREAD

**Issue by mwittrock** [SAP-docs/btp-integration-suite#20]
### Issue description

Hi there

In the "Request Headers" section, the documentation states that Content-Type request headers will be excluded from HTTP requests, even if specified in the "Request Headers" field:

> All Camel-specific headers (that starts with camel or org.apache.camel) and the below listed HTTP protocol headers are excluded even if you specify them.

(And Content-Type is in the list mentioned.)

However, if a Content-Type header is created in a Content Modifier, it is in fact included in the HTTP request to the external system. This happens regardless of whether the header is specified in the Request Headers field or not.

It seems to me that the behaviour is correct here, and that the documentation is therefore incorrect.

All the best,

Morten

### Feedback Type (Optional)

other

### Page Title on SAP Help Portal (prefilled)

HTTP Receiver Adapter

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/http-receiver-adapter?version=Cloud

**Comment by AnnikaGonnermann** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by mwittrock** [comment]
https://people.sap.com/mnw

**Comment by Karunaharan** [comment]
Hi @mwittrock ,
Morten, I'm looking into this feedback. Looks like a valid one to me as well. I'll keep you posted.

Regards,
Karuna

**Comment by Karunaharan** [comment]
Hi @mwittrock,
We tested this case and your feedback is valid. We will update the documentation in a few days.

Regards,
Karuna
