### ISSUE TITLE
Linked Pages are blank.

### ISSUE THREAD

**Issue by eakucuk** [SAP-docs/btp-integration-suite#24]
### Issue description

For IBM DB2 JDBC Drivers, the supported versions are not reachable. The links are expired. Could you please renew them? 

Thank you.

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Configure JDBC Drivers

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/configure-jdbc-drivers

**Comment by AnnikaGonnermann** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by Karunaharan** [comment]
Hi @eakucuk - both the links are working. Could you pls let us know which of them is not working?
https://www.ibm.com/support/pages/node/6241980
https://www.ibm.com/support/pages/node/6438025

Regards,
Karuna
