### ISSUE TITLE
Please add info about Entitlement

### ISSUE THREAD

**Issue by daniil-bolobonov** [SAP-docs/btp-integration-suite#25]
### Issue description

Please add the info that integration-assessment entitlement should be added to Subaccount as a prerequisite for creating 
Integration Assessment (integration-assessment) Service Instance.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Creating Service Instance and Service Key to enable API calling

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/creating-service-instance-and-service-key-to-enable-api-calling

**Comment by AnnikaGonnermann** [comment]
Hey @daniil-bolobonov  - thank you so much for your feedback! We've adapted the documentation! Best regards!

**Comment by daniil-bolobonov** [comment]
https://people.sap.com/daniil.bolobonov

From: sap-doc-bot[bot] ***@***.***>
Date: Wednesday, 13. December 2023 at 13:02
To: SAP-docs/btp-integration-suite ***@***.***>
Cc: Bolobonov, Daniil ***@***.***>, Mention ***@***.***>
Subject: Re: [SAP-docs/btp-integration-suite] Please add info about Entitlement (Issue #25)

Thank you for your valuable feedback contribution, @daniil-bolobonov<https://github.com/daniil-bolobonov>! So that we can recognize your contribution in SAP Community<https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md>, please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:

https://people.sap.com/your-user-name

Thanks!

**Comment by AnnikaGonnermann** [comment]
https://people.sap.com/daniil.bolobonov
