### ISSUE TITLE
Typo in the the Integration Suite Oauth 2 documentation

### ISSUE THREAD

**Issue by Santaneel** [SAP-docs/btp-integration-suite#28]
### Issue description

The issue is at - https://help.sap.com/docs/cloud-integration/sap-cloud-integration/oauth-2-0#oauth-2.0-authorization-code-grant 

Please check the image below. The text 'used).' needs re-wording or has to be removed 

![image](https://github.com/SAP-docs/btp-integration-suite/assets/17881202/c6207027-bef0-452b-896f-5b9402587a29)

### Feedback Type (Optional)

incorrect statement

### Page Title on SAP Help Portal (prefilled)

OAuth 2.0

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/oauth-2-0#loio508a70db7eac4addbb6ac69a06d46e79

**Comment by SrutiSagaram** [comment]
@Santaneel Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by pe-gu** [comment]
Thank you a lot for your feedback! I have updated the typo, and the changed topic will be visible after the next patch in a few days.

**Comment by pe-gu** [comment]
Thank you a lot for your feedback!

**Comment by Santaneel** [comment]
https://people.sap.com/santaneelods
