### ISSUE TITLE
Non-idiomatic use of semicolons in Groovy code samples

### ISSUE THREAD

**Issue by mwittrock** [SAP-docs/btp-integration-suite#3]
https://help.sap.com/docs/SAP_INTEGRATION_SUITE/51ab953548be4459bfe8539ecaeee98d/148851bf8192412cba1f9d2c17f4bd25.html

(This applies to all of this page's subpages that contain Groovy code.)

Ending statements with a semicolon in Groovy is not idiomatic. It is quite literally the first point in the [style guide](https://groovy-lang.org/style-guide.html) :-) Also, some code examples in these pages use semicolons while others don't, so the usage is not consistent (even within the same piece of code).

I propose that all Groovy code samples omit the semicolons to be in line with the Groovy style guide.

**Comment by DavidMitreski5** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by fippu82** [comment]
The same could be told about the Groovy code template that is included in every new Groovy script upon creation. But that's not a documentation input so I guess this is the wrong place to discuss this. :-)
