### ISSUE TITLE
SAP Integation Suite user access documentation incorrect

### ISSUE THREAD

**Issue by cvd75** [SAP-docs/btp-integration-suite#30]
### Issue description

Hi
As it is now it's possible to interpret that PI_Administrator role collection contains PI_Developer and PI_Business_Expert role collections as well which it doesn't. PI_administrator role is missing PI_Developer role collection for instance.

### Feedback Type (Optional)

incorrect statement

### Page Title on SAP Help Portal (prefilled)

Configuring User Access

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/configuring-user-access

**Comment by MelanieCueppers** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by Karunaharan** [comment]
hi @cvd75 - PI_Administrator role collection includes every task that can be done in the Cloud Integration capability of the Suite. The same is presented in the documentation as well.

PI_Administrator role collection includes the PI_Integration_Developer role collection which in turn includes the PI_Business_Expert role collection. Hope this is clear.

Regards,
Karuna

**Comment by cvd75** [comment]
We tested this, we have given PI_Administrator and this does not have the option to develop. Please do some testing and update documentation.
Regards,
Caroline

**Comment by Karunaharan** [comment]
Hi @cvd75 
Thanks for the feedback.
A couple of engineers who are responsible for user access are unavailable owing to the vacation season. I’ll look into this feedback as soon as they are back and update you.

Regards,
Karuna

**Comment by Karunaharan** [comment]
Hi @cvd75,
We have tested your feedback and found it correct. We will update the documentation accordingly and republish the same in the next available window.

Regards,
Karuna
