### ISSUE TITLE
Missing info about Request Headers added by CI when executing outbound call

### ISSUE THREAD

**Issue by daniil-bolobonov** [SAP-docs/btp-integration-suite#31]
### Issue description

Hello, 

It seems that some of the headers that Cloud Integration adds when executing a call to an outbound endpoint are missing.

E.g., I did the test with calling https://httpbin.org/anything via Postman and got this response:
`{
    "args": {
    },
    "data": "",
    "files": {
    },
    "form": {
    },
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate, br",
        "Cache-Control": "no-cache",
        "Host": "httpbin.org",
        "Postman-Token": "819fa066-7e12-4e00-b143-c4e524462d7f",
        "User-Agent": "PostmanRuntime/7.36.0",
        "X-Amzn-Trace-Id": "Root=1-65817397-412c4dbf12f281c717312722"
    },
    "json": null,
    "method": "GET",
    "origin": "176.199.252.237",
    "url": "https://httpbin.org/anything"
}`

When executing the call to the same endpoint but via Cloud Integration passthrough iFlow I get this response

`{
    "args": {
    },
    "data": "",
    "files": {
    },
    "form": {
    },
    "headers": {
        "Accept": "*/*",
        "Host": "httpbin.org",
        "Sap-Passport": "2A54482A0300E600004350495F696E746567726174696F6E776F726B73686F702D667A687136366673000000000000000000000000000000000000000000000000000000000000000000004D657373616765526563657074696F6E00000000000000000000000000000000000000000000000000004350495F696E746567726174696F6E776F726B73686F702D667A6871363666733439383337653339316138313439623339306364366266663366626330303766000000001649837E391A8149B390CD6BFF3FBC007FFA57551C7B31406194486B7BD019678600000001000000002A54482A",
        "Traceparent": "00-3ab905d4759c3ea24a3877ef104ba562-e4e3b95e101df7c1-01",
        "Tracestate": "97339250-69d2b3b0@dt=fw4;18;d0cff89;12417;2;0;0;310;9895;2h01;3h0d0cff89;4h012417;5h01;6h3ab905d4759c3ea24a3877ef104ba562;7he4e3b95e101df7c1",
        "User-Agent": "AHC/2.1",
        "X-Amzn-Trace-Id": "Root=1-65817362-2af40cf1039e7b79419e7759",
        "X-Dynatrace": "FW4;1775416240;24;218955657;74775;2;-1758227888;784;9895;2h01;3h0d0cff89;4h012417;5h01;6h3ab905d4759c3ea24a3877ef104ba562;7he4e3b95e101df7c1"
    },
    "json": null,
    "method": "GET",
    "origin": "3.64.88.217",
    "url": "https://httpbin.org/anything"
}`

Here I can see some of the headers that are being added by CI: `Traceparent`, `Tracestate`, `X-Dynatrace`. Hower, there is no info about this headers in the [docu](https://help.sap.com/docs/cloud-integration/sap-cloud-integration/headers-and-exchange-properties-provided-by-integration-framework). 

Can we please add the info about these Headers?

Thanks and best regards,
Daniil

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Headers and Exchange Properties Provided by the Integration Framework

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/headers-and-exchange-properties-provided-by-integration-framework

**Comment by AnnikaGonnermann** [comment]
Hey @daniil-bolobonov. Thanks for your feedback. We'll look into it and get back to you!

**Comment by AnnikaGonnermann** [comment]
Hey @daniil-bolobonov  - we are still working on it. Thanks for your patience!

**Comment by pe-gu** [comment]
Hello @daniil-bolobonov,
thank you again for your valuable contribution!
The headers and exchange properties listed in the documentation are those set by the Camel framework, and we try to make sure that these are documented according to our best knowledge.
However, certain additional headers can also be set by other network components, for example, proxies at SAP or customer side. We can't document all these network-related headers, these are also outside the control of SAP Cloud Integration. That's why you notice headers that are not covered in our documentation.
