### ISSUE TITLE
String separator clarification

### ISSUE THREAD

**Issue by bdbais** [SAP-docs/btp-integration-suite#32]
### Issue description

Is it possible to show a correct xsd for this Object and explain behavior with characters separator inside string? 

### Feedback Type (Optional)

examples or samples

### Page Title on SAP Help Portal (prefilled)

Configure CSV to XML Converter

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/configure-csv-to-xml-converter#prerequisites

**Comment by SrutiSagaram** [comment]
Hey @bdbais! Thanks for your feedback. We'll look into it and get back to you!

**Comment by Karunaharan** [comment]
Hi @bdbais 
An example or sample is usually not in the scope of the documentation. Also, we can't share a "correct" XSD as it varies from one customer to another.

Anyway, we take this feedback seriously and have created a quality backlog to improve our documentation shortly. 

Hope this helps!

Regards,
Karuna
