### ISSUE TITLE
java version 1.7

### ISSUE THREAD

**Issue by ottfro1** [SAP-docs/btp-integration-suite#33]
### Issue description

8. In the Execution Environment drop-down list box, select java version JavaSE-1.7 or lower.

Is the text above correct? JavaSE-1.7 is legacy and obsolete and the text should be JavaSE-1.8 ?

If JavaSE-1.7 is correct then libraries supporting java 1.8 can not be used.
There should be an explanation to why  JavaSE-1.7 must be selected and why JavaSE-1.8 is not supported.
Even java 1.8 is old and it is hard to find uptodate libraries - Apache ActiveMQ and IBM WebsphereMQ does not ship JMS drivers for java 1.8 anymore and the same for many other libraries - the latest library version does not support javaSE-1.8.

### Feedback Type (Optional)

incorrect statement

### Page Title on SAP Help Portal (prefilled)

Create OSGi Bundle

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/create-osgi-bundle

**Comment by SrutiSagaram** [comment]
Hey @ottfro1 
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by Karunaharan** [comment]
Hi @ottfro1 - SAP Integration Suite doesn't support javeSE 1.8 and above yet. We will look into the feedback in detail and get back.

Regards,
Karuna
