### ISSUE TITLE
IS(Integration Suite) JDBC adapter related inquiry

### ISSUE THREAD

**Issue by I345642** [SAP-docs/btp-integration-suite#34]
### Issue description

Hi team,
I am writing to you with regards to inquiries about the IS (Integration Suite) JDBC adapter.
 
1. Background of the inquiry:
1) Upon reviewing the SAP help document "JDBC Receiver Adapter," it appears that UPSERT operations are currently not supported in XML SQL format.
Note:
UPSERT operation is currently not supported for XML SQL format. It’s recommended to use stored procedure to update an existing record. If the record doesn’t exist, then use INSERT.
https://help.sap.com/docs/cloud-integration/sap-cloud-integration/jdbc-receiver-adapter

2) However, in the "Payload and Operation" section, there is a guide on how to create UPDATE INSERT operations in XML format, and through actual testing, we have confirmed that JDBC UPDATE INSERT (UPSERT) operations can be performed using IS development as shown below.
https://help.sap.com/docs/cloud-integration/sap-cloud-integration/payload-and-operation
 
2. Inquiry:
1) We would like to inquire if it is possible to develop UPDATE INSERT operations in XML format in IS (Integration Suite), as stated in the content of the following link, similar to the existing PO product.
https://help.sap.com/docs/cloud-integration/sap-cloud-integration/payload-and-operation
 
2) We would like to inquire about the content of the following note, whether it refers to a different development method for the UPDATE INSERT operation mentioned above, or if it is an outdated or incorrectly stated information.
Note:
UPSERT operation is currently not supported for XML SQL format. It’s recommended to use stored procedure to update an existing record. If the record doesn’t exist, then use INSERT.
https://help.sap.com/docs/cloud-integration/sap-cloud-integration/jdbc-receiver-adapter

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

JDBC Receiver Adapter

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/jdbc-receiver-adapter

**Comment by SrutiSagaram** [comment]
Hey @I345642! Thanks for your feedback. We'll look into it and get back to you!

**Comment by Karunaharan** [comment]
Hi @I345642,
Your feedback is right. UPSERT operation is not supported. 
At the same time, the note in the documentation is valid too. The UPDATE_INSERT operation is developed as a custom operation.
The reason why the UPSERT operation is not supported is that not all database vendors straightforwardly support this operation. We didn't want to introduce UPSERT operation only for a certain database. Hence, the note in the documentation.

Could you please tell me which database do you use?
If your database supports UPSERT operation, you can continue to use the UPDATE_INSERT operation as an alternative.

Hope this helps!

Regards,
Karuna

**Comment by I345642** [comment]
Hi Karuna,
Thanks for your response!

"Could you please tell me which database do you use?" 
The database vendors used in our project is as follows.
- ORACLE 12c
- MS SQL Server 2014 / MS SQL Server 2016
Could I inquire whether UPDATE_INSERT function can be used?

I would appreciate your support.
BR,
Chloe
VCSP
