### ISSUE TITLE
eclipse create OSGI bundle

### ISSUE THREAD

**Issue by ottfro1** [SAP-docs/btp-integration-suite#35]
### Issue description

What should be selected?
In eclipse you can choose between 

Analyze library contents and add dependencies
1 selected 
2 unselected

9. In the Target Platform, select an OSGi framework option.
1 Equinox
2 standard

Unzip JAR archives : 
1 selected 
2 unselected

Update references to jar files
1 selected 
2 unselected

For us developers used to building sap po adapter modules and java mappings it would be helpful with guidance

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Create OSGi Bundle

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/create-osgi-bundle?q=Configure%20APIs

**Comment by Karunaharan** [comment]
Hey @ottfro1
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by HarshitaSuryavanshi** [comment]
Hi @ottfro1,
You can follow this blog: https://community.sap.com/t5/technology-blogs-by-sap/sap-cpi-adapter-development-consuming-an-external-jar-into-an-adapter/ba-p/13382631  
to use an external service which is non-osgi.

We are in process of updating our Help portal documentation.

**Comment by HarshitaSuryavanshi** [comment]
Issue similar to https://github.com/SAP-docs/btp-integration-suite/issues/39
