### ISSUE TITLE
more documentation needed

### ISSUE THREAD

**Issue by ottfro1** [SAP-docs/btp-integration-suite#37]
### Issue description

It would be good if it was documented

Is the adapter using Sharepoint REST API v1 or v2? 
https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service
This is important to know to be able to do the app registration and setup authorizations correctly.
It would be good if the documentation detailed how to do the app registration.

What is the maximum file size supported?

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Microsoft SharePoint Adapter

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/microsoft-sharepoint-adapter

**Comment by SrutiSagaram** [comment]
Hi @ottfro1. 
Thank you for the feedback. We’ll look into it and come back to you if we have any questions.

**Comment by Karunaharan** [comment]
Hi @ottfro1,
The adapter supports v2 APIs. We will get this added to your documentation shortly and republish it in the next available window.

Regards,
Karuna

**Comment by ottfro1** [comment]
> Thank you for your valuable feedback contribution, @ottfro1! So that we can [recognize your contribution in SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:
> 
> ```
> https://people.sap.com/your-user-name
> ```
> 
> Thanks!

https://people.sap.com/otto.frost4
