### ISSUE TITLE
Incorrect instruction for URI of Cloud Integration UI

### ISSUE THREAD

**Issue by CimermanDenis** [SAP-docs/btp-integration-suite#38]
### Issue description

Maybe I am wrong, but I don't think this statement is correct anymore: "Check out the address of your Cloud Integration user interface (Web UI). It ends with /itspaces." I think it ends with shell/* now.

### Feedback Type (Optional)

incorrect statement

### Page Title on SAP Help Portal (prefilled)

HTTP Calls and URI Components

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/http-calls-and-uri-components

**Comment by AnnikaGonnermann** [comment]
Hey @CimermanDenis - thank you for your contribution. We will look into it and get back to you in case of questions!
Best
Annika

**Comment by pe-gu** [comment]
Hello https://github.com/CimermanDenis, many thanks for your contribution! You are right! The URL ends now with 
 **/itspaces/shell/integration** in the Neo environment. I have corrected the documentation topic, and the change will become visible in the next few days.

**Comment by CimermanDenis** [comment]
https://people.sap.com/deniscimerman

________________________________
