### ISSUE TITLE
I propose to explain out how is the integration process - Read invoked. A screenshot of the DS adapter would be useful for a better understanding, too.

### ISSUE THREAD

**Issue by CimermanDenis** [SAP-docs/btp-integration-suite#40]
### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Decouple Sender and Flows Using Data Store

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/decouple-sender-and-flows-using-data-store

**Comment by MelanieCueppers** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by AnnikaGonnermann** [comment]
Hey @CimermanDenis, thanks for your feedback. At the beginning of the text under "implementation" we provide more information:

"The integration flow consists of 2 integration processes:

The Integration Process - Write integration process receives the request from the client, writes the request in a data store, and sends back a response to the calling client.

The Integration Process - Read integration process reads the request from the same data store, and then performs the actual long running service call and (eventually) further message orchestration steps."

Is that what you had in mind?

To get more information about the configuration, you can download the package or check it out in the Business Accelerator Hub: https://api.sap.com/integrationflow/ModelingBasics_DecoupleFlowsUsingPersistence

Best
Annika

**Comment by CimermanDenis** [comment]
Hi Annika,

I would rather stress out that it is not the read process, which polls the data store just out of nothing or based on a timer, but there is (probably) a monitoring applications which initiates the read process. IMHO, this just be really stated to make the whole concept digestible.

What do you think?

Regards
Denis


________________________________

**Comment by AnnikaGonnermann** [comment]
Hey @CimermanDenis  - thanks for specifying! I've made the following adjustments:

The Integration Process - Read integration process **polls** the request from the same data store, and then performs the actual long running service call and (eventually) further message orchestration steps.

Hopefully that should help avoid confusion in the future!

Best
Annika
