### ISSUE TITLE
The you tube videos referenced on this page have been set to private and so are no longer visible

### ISSUE THREAD

**Issue by katansapdevelop** [SAP-docs/btp-integration-suite#41]
### Feedback Type (Optional)

linking

### Page Title on SAP Help Portal (prefilled)

Working with a Message Implementation Guideline

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/working-with-message-implementation-guideline?locale=zh-CN%3Flocale%3Dzh-CN

**Comment by SrutiSagaram** [comment]
Hi @katansapdevelop 
Thank you for your feedback, we will look into it and get back to you.

**Comment by RanjithaSathiarajS** [comment]
Hi @katansapdevelop ,

This issue has been resolved.
