### ISSUE TITLE
Is packaging/bulking supported? 

### ISSUE THREAD

**Issue by ottfro1** [SAP-docs/btp-integration-suite#42]
### Issue description

Is packaging/bulking supported?

 If not supported that should be mentioned. 

If supported - then how to configure?

The packaging/bulking feature is one of the most important features and reasons to use SAP CI - if this is missing then not much point in using this product. Sending one message at a time results in very bad performance. Migrating from SAP PO - this feature is essential and a show stopper if missing.

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Configure the XI Receiver Adapter

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/configure-xi-receiver-adapter

**Comment by SrutiSagaram** [comment]
Hi @ottfro1 

Thank you for your feedback. We are looking into it and will get back to you.

**Comment by pe-gu** [comment]
Thank you for your question! Bulk messages are not supported for this adapter, and I added a statement in the documentation (which will be visible in a few days in the public version). We can give no information on planned features in the documentation. If this feature is supported in the future, we will adjust the documentation accordingly. Please check the [roadmap](https://[roadmap](https://roadmaps.sap.com/welcome)s.sap.com/welcome) regularly to get to know when this feature is planned to be released.
