### ISSUE TITLE
http parameters

### ISSUE THREAD

**Issue by ottfro1** [SAP-docs/btp-integration-suite#45]
### Issue description

In SAP PO we have the parameters below 
The parmeters are essential for the functionality
In SAP PO is is a big mess - some paramters are missing for SOAP and others missing for REST - very inconsistent- the http_aae is not in line at all

SOAP receiver adapter (relevant for SENDER too)
XMBWS.XMLEncoding
XMBWS.TransferEncoding
XMBWS.Encoding
XMBWS.AcceptEncoding
hostVerification

REST receiver adapter
useAuthPreemptive
http.expectContinue 
http.enableExpectContinueOver 
httpChunkStream boolean 
minSSLVersion  
maxSSLVersion 
validateBasicConstraints boolean 
verifyHostname boolean 
http.nonProxyHosts 
transferCookieOnRedirect
propagatePrincipal 
useUTF8CredentialsEncoding 
useAuthPreemptive 
overrideHttpMethod

what are the corresponding parameters in SAP CI for soap and rest?
all paramters are essential for soap and rest and should be documented 
when migrationg from SAP PO to CI all the parameters must be working
It should be documented what the CI corresponding CI parameters are
If parameters are missing it should be documented

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

HTTP Receiver Adapter

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/http-receiver-adapter?q=xi%20adapter

**Comment by SrutiSagaram** [comment]
Hi @ottfro1 
Thank you for your feedback. We will look at it and get back to you.

**Comment by ottfro1** [comment]
In PO many of the parameters can only be set at design time.
You want to be able to set the parameters by code at runtime.

**Comment by Karunaharan** [comment]
Closing this issue as the same query is asked in https://github.com/SAP-docs/btp-integration-suite/issues/46

Regards,
Karuna
