### ISSUE TITLE
http parameters

### ISSUE THREAD

**Issue by ottfro1** [SAP-docs/btp-integration-suite#46]
### Issue description

In SAP PO we have the parameters below - 
The parmeters are essential for the functionality
In SAP PO it is a big mess - some paramters are missing for SOAP and others for REST - very innconsistent - not to mention httt_aae

SOAP receiver adapter (relevant for SENDER too)
XMBWS.XMLEncoding
XMBWS.TransferEncoding
XMBWS.Encoding
XMBWS.AcceptEncoding
hostVerification

REST receiver adapter
useAuthPreemptive
http.expectContinue 
http.enableExpectContinueOver 
httpChunkStream boolean 
minSSLVersion  
maxSSLVersion 
validateBasicConstraints boolean 
verifyHostname boolean 
http.nonProxyHosts 
transferCookieOnRedirect
propagatePrincipal 
useUTF8CredentialsEncoding 
useAuthPreemptive 
overrideHttpMethod

what are the corresponding parameters in SAP CI for soap and rest?
all paramters are essential for soap and rest
when migrationg from SAP PO to CI all the parameters must be working
It should be documented what the CI corresponding CI parameters are

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Configure the SOAP (SOAP 1.x) Receiver Adapter

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/configure-soap-soap-1-x-receiver-adapter?q=xi%20adapter

**Comment by SrutiSagaram** [comment]
Hi @ottfro1 

Thank you for your feedback. We will look at this and get back to you.

Regards,
Sruti

**Comment by ottfro1** [comment]
In PO many of the parameters can only be set at design time.
You want to be able to set the parameters by code at runtime.

**Comment by Karunaharan** [comment]
Hi @ottfro1 
I would like to know why you want to know the equivalent parameters in Cloud Integration. Are you planning to migrate your ICOs to SAP Integration Suite? If that is the case, [Migration Tooling](https://help.sap.com/docs/integration-suite/sap-integration-suite/migration-tooling) of Cloud Integration should help you to migrate in a semi-automatic way.
As of now, we don't publish/expose every parameter in Cloud Integration.

Please let me know.

Regards,
Karuna

**Comment by ottfro1** [comment]
The migration tooling does not work for many of our ICOs - we need to do manual migration.

The parameters are necessary for many of our scenarios. 

If the parmeter settings are missing it is necessary to know what is the hardcoded value of the parameters in sap ci.

Some scenarios requires the parameters to be set while for others the parameters must not be set.

**Comment by Karunaharan** [comment]
Hi @ottfro1,
Thanks for your inputs. I would recommend you creating a support ticket on the component LOD-HCI-PI-WT-IFL. This GitHub respository can only handle feedback for documentation. Your inputs/requests are beyond the scope of this repo.

Regards,
Karuna
