### ISSUE TITLE
Is this guide applicable for Integration Suite?

### ISSUE THREAD

**Issue by daniil-bolobonov** [SAP-docs/btp-integration-suite#48]
### Issue description

Is this example scenario applicable for Integration Suite? 
The link for configuring [OAuth SAML Bearer Destination](https://help.sap.com/docs/integration-suite/sap-integration-suite/f93122629816412c911f827a5eb62e5e.html?locale=en-US&version=CLOUD) leads to Neo section.

Maybe better to refer to this blog series? https://community.sap.com/t5/technology-blogs-by-sap/principal-propagation-in-sap-integration-suite/ba-p/13528717

### Feedback Type (Optional)

outdated information

### Page Title on SAP Help Portal (prefilled)

Setting Up Principal Propagation (Example Scenario)

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/setting-up-principal-propagation-example-scenario?locale=en-US&version=CLOUD

**Comment by MelanieCueppers** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by pe-gu** [comment]
Thank you for your feedback!
We corrected the documentation by separating Neo-specific information. For Cloud Foundry, we provide the link to the blog series as mentioned.
The SAP Cloud Integration documentation (contains Neo- and Cloud Foundry-specific information): [Setting Up Principal Propagation (Example Scenario) | SAP Help Portal](https://help.sap.com/docs/cloud-integration/sap-cloud-integration/setting-up-principal-propagation-example-scenario)
The SAP Integration Suite documentation (doesn’t contain Neo-specific information): [Setting Up Principal Propagation (Example Scenario) | SAP Help Portal](https://help.sap.com/docs/integration-suite/sap-integration-suite/setting-up-principal-propagation-example-scenario)
