### ISSUE TITLE
The nested multicast restriction should be added to the documentation

### ISSUE THREAD

**Issue by vinben06** [SAP-docs/btp-integration-suite#52]
### Issue description

The limitation explained in the **_SAP Note 3028577 - Exception Subprocess in SAP Cloud Integration does not execute in case of error on nested multicast branches_** - should also be documented directly into the Multicast description page to prevent developers from running into this comonly faced problem.

Regards
Vincent

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Define Multicast

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/define-multicast?q=multicast

**Comment by SrutiSagaram** [comment]
Hi @vinben06 

Thank you for your feedback. We will look at the feedback and get back to you.

**Comment by Karunaharan** [comment]
Hi @vinben06,
Your feedback is valid. We are already working to fix the gap. Thanks for the patience!

**Comment by Karunaharan** [comment]
Hi @vinben06 
The changes that you requested are added to the documentation. The changes will be available in the next week.
