### ISSUE TITLE
CamelSplitIndex is property?

### ISSUE THREAD

**Issue by gaborperak** [SAP-docs/btp-integration-suite#53]
### Issue description

Hi!

The documentation says we can get the split index dynamically, but it refers to it as a header variable, but I think this is a property variable:

<img width="1572" alt="image" src="https://github.com/SAP-docs/btp-integration-suite/assets/152374831/a0142899-8467-441a-ae29-376e97e740be">

<img width="1274" alt="image" src="https://github.com/SAP-docs/btp-integration-suite/assets/152374831/54d94301-ab9b-4d3a-be8d-8375a4a6ea8e">

### Feedback Type (Optional)

incorrect statement

### Page Title on SAP Help Portal (prefilled)

Define Iterating Splitter

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/PRODUCT_ID/368c481cd6954bdfa5d0435479fd4eaf/d61d6ecc8c8d453baa95c59e85f9cab1.html?state=PRODUCTION&version=Cloud&locale=en-GB

**Comment by pe-gu** [comment]
Hello @gaborperak,
Yes, you are right!
I have corrected this issue. The change is visible after the next documentation patch, likely in the next few days.
I the following topic, it is correctly stated that it’s a property.
[Headers and Exchange Properties Provided by the Integration Framework | SAP Help Portal](https://help.sap.com/docs/cloud-integration/sap-cloud-integration/headers-and-exchange-properties-provided-by-integration-framework)

**Comment by pe-gu** [comment]
Thank you for your input!
