### ISSUE TITLE
Page "Configure the AMQP Sender Adapter" removes text "SAP Cloud Integration"

### ISSUE THREAD

**Issue by davidcalloway** [SAP-docs/btp-integration-suite#55]
### Issue description

When browsing the documentation on the page https://help.sap.com/docs/cloud-integration/sap-cloud-integration/configure-amqp-sender-adapter I noticed there was some text that didn't make sense (see screenshot)

The source markdown makes more sense: https://github.com/SAP-docs/btp-integration-suite/blob/main/docs/ci/Development/configure-the-amqp-sender-adapter-99ce674.md 

It appears that something in the build process is replacing the text "SAP Cloud Integration" from the Note.

![2024-04-09-SAP-AMQP-Adapter-Error](https://github.com/SAP-docs/btp-integration-suite/assets/423111/dcb6b5c4-eb82-4034-a2b8-2b653b6e11cd)

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Configure the AMQP Sender Adapter

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/configure-amqp-sender-adapter

**Comment by MelanieCueppers** [comment]
Hi @davidcalloway, thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by pe-gu** [comment]
Hi @davidcalloway, you are right. Ths is a problem with some metadata not applied correctly. I have corrected the issue and the change will be seen after our next documentation patch (very likely happening within the next 2 days).
Many thanks for your contribution!

The Text now reads in the following way: 
_Queues, topics, and messages can only be monitored by using tools provided by the message broker provider. Those monitors are not integrated into SAP Cloud Integration. Using SAP Cloud Integration, you can only monitor the integration flows using the AMQP adapter and the messages that are sent to or consumed from the message broker._

**Comment by pe-gu** [comment]
Many thanks for your contribution!
