### ISSUE TITLE
Subscribing and Configuring Initial Access to SAP Integration Suite requires clearing of cached data too

### ISSUE THREAD

**Issue by dsimov** [SAP-docs/btp-integration-suite#58]
### Issue description

Please expand the content of the topic to include a step or instructions for clearing the historic/cached data. I just tested on Safari - accessing the Integration Suite application did not become possible until I cleared the cache, cookies, local storage, and HSTS Policy.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Subscribing and Configuring Initial Access to SAP Integration Suite

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_INTEGRATION_SUITE/51ab953548be4459bfe8539ecaeee98d/8a3c8b7a6b1c4f249bb81d11644ef806.html

**Comment by SrutiSagaram** [comment]
Hi @dsimov 

Thank you for your feedback. We will check and get back to you as soon as possible.

**Comment by SrutiSagaram** [comment]
@dsimov 

I'm sorry for the delay, my team is still checking this.

**Comment by SrutiSagaram** [comment]
@dsimov Thank you for your patience. My team has checked this, and it's updated in the document in a note.
