### ISSUE TITLE
Disk limit (or circuit breaker) for MPL obsolete on CF

### ISSUE THREAD

**Issue by fippu82** [SAP-docs/btp-integration-suite#59]
### Issue description

As far as I know, the disk limit (or is it only the circuit breaker?) for MPL (attachments) has been lifted on Cloud Foundry. Therefore, the text here should be updated accordingly. 

### Feedback Type (Optional)

outdated information

### Page Title on SAP Help Portal (prefilled)

Persist Messages

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/persist-messages

**Comment by Karunaharan** [comment]
Hi @fippu82 
Thank you for your feedback. We will check and get back to you as soon as possible.

**Comment by pe-gu** [comment]
Hello @fippu82,
Thanks a lot for your input! I have enhanced the documentation accordingly.

**Comment by pe-gu** [comment]
Hello @fippu82,
Thanks a lot for your input! I have enhanced the documentation accordingly.
