### ISSUE TITLE
Incomplete List of Role Templates for Cloud Foundry / Missing Persona Definitions

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-integration-suite#60]
### Issue description

The table on the page lists the Role Templates for Cloud Foundry for Integration Suite, but does not contain the Role Templates that are used in the default Role Collections (e.g. AuthGroup_IntegrationDeveloper). There is no transparency which single Role Templates are contained in which compound roles (AuthGroup_*), which makes it very hard, to derive a custom PI_Developer Role Collection using Access Policies.

The Tasks "Export Package for transport", "Import Package from transport" and "Update Package from transport" are not assigned to a Persona ("n.a."). In my opinion this should be either Integration Developer in the Development System to export the package for transport or the Tenant Admin / Integration Owner to import the transports in the test or production tenants. 

Missing Role Templates in the table are:
- AccessAllAccessPoliciesArtifacts
- AccessPoliciesEdit
- AccessPoliciesRead
- AuthGroup_Administrator
- AuthGroup_BusinessExpert
- AuthGroup_ContentPublisher
- AuthGroup_IntegrationDeveloper
- DataStoresAndQueuesConfig
- ExternalLoggingActivate
- ExternalLoggingActivationRead
- HealthCheckMonitoringDataRead
- IntegrationCellOperationCockpitRead
- IntegrationCellOperationCockpitWrite
- MonitoringArtifactsDeploy
- QueuesActivate
- QueuesRetry
- WorkspaceArtifactLocksDelete
- WorkspaceArtifactLocksRead
- WorkspaceDesignGuidelinesConfigure

Kind regards,
Sebastian

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Tasks and Permissions

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/tasks-and-permissions-556d5575d4b0483e85d4f3251f21d0ec

**Comment by Karunaharan** [comment]
Hi @sebastianesch 
Thank you for your feedback. We will check and get back to you as soon as possible.

**Comment by sebastianesch** [comment]
My User ID is 3335

**Comment by pe-gu** [comment]
Hello @sebastianesch, 
the content has been updated. Thanks again for your input!
Sorry for the delay, due to sickness.
Peter
