### ISSUE TITLE
Video ist norworking

### ISSUE THREAD

**Issue by ChristianW02** [SAP-docs/btp-integration-suite#63]
### Issue description

Video on page ist not working. page: https://help.sap.com/docs/cloud-integration/sap-cloud-integration/sap-integration-advisor?locale=en-US

### Feedback Type (Optional)

other

### Page Title on SAP Help Portal (prefilled)

SAP Integration Advisor

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/PRODUCT_ID/368c481cd6954bdfa5d0435479fd4eaf/6b9fe2d753534bebadcfa9080228bd94.html?state=PRODUCTION&version=Cloud&locale=en-US

**Comment by SrutiSagaram** [comment]
@ChristianW02  Thank you for your feedback, we will take a look and get back to you.

**Comment by Karunaharan** [comment]
Hi @ChristianW02 
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by RanjithaSathiarajS** [comment]
Hello @ChristianW02 , thank you for the feedback. The video has been removed from the chapter.
