### ISSUE TITLE
API Roles unclear

### ISSUE THREAD

**Issue by bauer-at-work** [SAP-docs/btp-integration-suite#64]
### Issue description

Column `Role that you must be assigned to…`:   
Is is sufficient to have one of the multiple roles per cell assigned or do I need all of them to be granted to my user?
The documentation does not tell me that yet.

Also, the bullet points are used inconsequently.

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Configure the API business hub enterprise [New Design]

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/configure-api-business-hub-enterprise-new-design

**Comment by MelanieCueppers** [comment]
Hi @bauer-at-work, Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by Kakabira** [comment]
Hi @bauer-at-work: We have addressed your comments. Please see: 
https://help.sap.com/docs/sap-api-management/sap-api-management/configure-api-business-hub-enterprise-new-design?version=Cloud
Please let us know if you have any further questions.

**Comment by bauer-at-work** [comment]
Hi @Kakabira,
unfortunately, my request is in context of SAP Integration Suite, not standalone APIM.
Compare the URL I provided and the one you sent.

Thanks
Michael

**Comment by Kakabira** [comment]
@bauer-at-work: Sorry, I sent the standalone APIM link mistakenly.
Here's the link to the SAP Integration Suite guide:
https://help.sap.com/docs/integration-suite/sap-integration-suite/configure-api-business-hub-enterprise-new-design?version=CLOUD

Thanks,
Kasturi

**Comment by bauer-at-work** [comment]
Ok thx for updating the Integration Suite docs as well. Looks better now.
