### ISSUE TITLE
Description of usage of <ValidateBasedOn> element is missing

### ISSUE THREAD

**Issue by daniil-bolobonov** [SAP-docs/btp-integration-suite#66]
### Issue description

Please add the info on how to use the <ValidateBasedOn> element as per apigee docu: https://docs.apigee.com/api-platform/reference/policies/access-control-policy#validatebasedon

I've tested and can confirm that APIM is capable of processing this element to control which IP addresses are evaluated.

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Access Control

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/access-control?version=CLOUD&q=access%20control

**Comment by MelanieCueppers** [comment]
Hi @daniil-bolobonov, Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by Kakabira** [comment]
Hi @daniil-bolobonov,

I have added the <ValidateBasedOn> element in the Integration Suite user guide. Please see: 
https://help.sap.com/docs/integration-suite/sap-integration-suite/access-control?version=CLOUD&q=access%20control

Thanks,
Kasturi

**Comment by daniil-bolobonov** [comment]
Hi @Kakabira,

Thank you for adding this info. Just one correction: as per my tests the default value of ValidateBasedOn element is X_FORWARDED_FOR_FIRST_IP. This is also mentioned in the note above. 
![image](https://github.com/SAP-docs/btp-integration-suite/assets/108473120/bfdb689b-d5cc-4fa4-bfe1-524940a6c37d)

Kind regards,
Daniil

**Comment by Kakabira** [comment]
Hi @daniil-bolobonov,

I have updated the default value. Please see, 
https://help.sap.com/docs/integration-suite/sap-integration-suite/access-control?version=CLOUD

Thanks,
Kasturi
