### ISSUE TITLE
Prerequisites regarding Entitlements are missing for Edge Integration Cell

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-integration-suite#68]
### Issue description

Please describe the required entitlements to enable Edge Integration Cell in the documentation.

See also #67. 

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Before You Start

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/before-you-start

**Comment by MelanieCueppers** [comment]
Hi @sebastianesch, thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by Karunaharan** [comment]
hi @sebastianesch,
The prerequisites are captured here: https://help.sap.com/docs/integration-suite/sap-integration-suite/activate-edge-integration-cell?version=CLOUD

Regards,
Karuna
