### ISSUE TITLE
Access Policies are missing from the Guidelines for non-transportable Content

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-integration-suite#69]
### Issue description

As per [SAP Note 3265467](https://me.sap.com/notes/0003265467) Access Policies can't be transported at the moment. The Guide for Handling Integration Artifacts that cannot be transported does not cover Access Policies.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Handling Integration Artifacts When Reusing an Integration Flow on Multiple Tenants

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/handling-integration-artifacts-when-reusing-integration-flow-on-multiple-tenants

**Comment by SrutiSagaram** [comment]
Hi @sebastianesch 

Thank you for your feedback, we will look into it and get back.

**Comment by pe-gu** [comment]
Dear @sebastianesch, many thanks for your feedback! I have updated the topic. Best regards, Peter

**Comment by pe-gu** [comment]
Dear @sebastianesch, many thanks for your feedback! I have updated the topic. Best regards, Peter
