### ISSUE TITLE
The dynamic configuration box is very unclear

### ISSUE THREAD

**Issue by mwittrock** [SAP-docs/btp-integration-suite#70]
### Issue description

The content of the last "Note" box on the page could be a lot clearer. First off, these expressions are not regular expressions but Simple Expression Language expressions. Second, spending more than half of the box explaining how headers are created in a Content Modifier is kind of burying the lede. The crucial information here is that the Destination field accepts dynamic values in the form of Simple expressions. The Destination field is not even mentioned by name in the box.

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

RFC Receiver Adapter

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/rfc-receiver-adapter?version=Cloud

**Comment by MelanieCueppers** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by HarshitaSuryavanshi** [comment]
Hi @mwittrock 
Thanks for your feedback. We have updated the topic, and the changes will be visible by tomorrow EOB.
