### ISSUE TITLE
More Details about external components & network setup to better understand EIC setup

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-integration-suite#71]
### Issue description

It would be very helpful to better understand and plan EIC setups, if all external components that are required are shown in the architecture diagram. We are currently discussing the Load Balancer integration with SUSE Rancher for an on-premise EIC setup. But the Load Balancer component is not shown in the architecture diagram.

To be able to communicate to other involved parties requirements regarding network setup, it would also help to shown in the diagram / or a new diagram, the network structure of the EIC setup. Showing external network (with the external IP shown in the EIC user interface) and internal network of the Kubernetes cluster.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Technical Landscape (Edge Integration Cell)

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/technical-landscape-edge?q=edge%20integration%20cell

**Comment by SrutiSagaram** [comment]
Hi @sebastianesch 
Thank you for the feedback, we will check and get back to you.

**Comment by AN-MALO** [comment]
Hi @sebastianesch 
Thank you for your feedback. I will discuss your suggestion with my colleagues and hope that we can offer a new version of the documentation that includes the desired changes soon.

**Comment by AN-MALO** [comment]
@sebastianesch : Could you please explain in more detail what do you mean with "Showing external network (with the external IP shown in the EIC user interface) and internal network of the Kubernetes cluster."? Thanks

**Comment by sebastianesch** [comment]
I would like to understand, e.g. where the external Loadbalancer has to point to (Istio or the Worker Nodes?) and who is responsible to distribute requests in the EIC to the workers. Is it a task of the external Loadbalancer or of the Istio component in EIC?

From the system landscape diagram this is not clear.

**Comment by AN-MALO** [comment]
Thanks for your answer!
We will adjust the diagram and add the Load Balancer. 
As the other questions pertain to Kubernetes or Istio concepts, they fall outside the scope of the Edge Integration Suite documentation and hence, are not covered within it.

**Comment by sebastianesch** [comment]
Then please link to the respective documentations for Kubernetes or SAP Edge Lifecycle Management. It does not help to disregard the surrounding topics, if you need to understand the whole picture to get Edge Integration Cell to work.

**Comment by AN-MALO** [comment]
Will do that! Thanks!
