### ISSUE TITLE
Wrong Source Message ID for ID Mapper

### ISSUE THREAD

**Issue by freest5** [SAP-docs/btp-integration-suite#72]
### Issue description

There is a mistake on the page for Source Message ID for both ID Mappings.
Current wrong: ${property.SplitMessageID}
Should be: ${header.SapMessageIdEx}

Refer to the IFlow design in the repository:
https://api.sap.com/integrationflow/PatternQualityOfService_Scenario04b

### Feedback Type (Optional)

incorrect statement

### Page Title on SAP Help Portal (prefilled)

ID Mapping (with Multicast)

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/id-mapping-with-multicast

**Comment by MelanieCueppers** [comment]
Hi @freest5, thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by pe-gu** [comment]
Hi @freest5, I'm sorry that there was another mistake in the Integration Flow Design Guidelines. I have corrected it immediately, and the change will be visible after a documentation patch later today. I also checked the other two scenarios with ID Mapper to see if a similar error occurred, but that was not the case. Thank you so much for your support!

**Comment by freest5** [comment]
Hi Peter, Hi Melanie,
Thank you for responding and maintaining the documentation,
Appreciate this!

Have a good day :)
Stan.

**Comment by pe-gu** [comment]
Hello Stan, thank YOU for your support! Best regards, Peter
