### ISSUE TITLE
Value is not defined for SAP RM receiver connection

### ISSUE THREAD

**Issue by freest5** [SAP-docs/btp-integration-suite#73]
### Issue description

In the table defining the SOAP (SAP RM) receiver adapter config:
Value of the parameter "Source for SAP RM Message ID" must be = ${header.orderNumber}
Now the value is equal to the parameter name = Source for SAP RM Message ID.

### Feedback Type (Optional)

spelling or grammar

### Page Title on SAP Help Portal (prefilled)

Aggregator

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/aggregator-pattern

**Comment by SrutiSagaram** [comment]
Hi @freest5 
 Thank you for your feedback. We will check and get back to you.

**Comment by pe-gu** [comment]
Hi @freest5, thanks a lot for your contribution! I have corrected the issue.

**Comment by freest5** [comment]
234689

**Comment by freest5** [comment]
Thank you a lot, Colleagues!
Have a great summer :)
