### ISSUE TITLE
Wrong copy-paste from another help page

### ISSUE THREAD

**Issue by freest5** [SAP-docs/btp-integration-suite#74]
### Issue description

On the page"Decoupling via Data Store" there is a text which is not relevant for this case:
"Because the retry is performed within the same instance of the message processing log, the message processing log ID and, as a result, the mapped unique ID remain the same."

Seems it is copy-paste from referenced "Decoupling via JMS Queue" page.

In the current Data Store case, MPL ID is not used as the unique ID, but the Data Store entry ID is used which is updated from ${property.orderNumber}, which in its turn is retrieved from the payload.

### Feedback Type (Optional)

incorrect statement

### Page Title on SAP Help Portal (prefilled)

Decoupling via Data Store

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/decoupling-via-data-store

**Comment by SrutiSagaram** [comment]
Hi @freest5 
Thank you for your feedback. We will take a look and get back.

**Comment by pe-gu** [comment]
Hello @freest5, thank you for your finding! I have corrected the mistake.

**Comment by freest5** [comment]
@pe-gu Thank you a lot, Peter! Best wishes, Stan.
