### ISSUE TITLE
Minor amendments to the text.

### ISSUE THREAD

**Issue by michael-eaton** [SAP-docs/btp-integration-suite#75]
### Issue description

These 2 sentences do not read very well.

_Based on the simulation result, you can decide whether to continue and deploy the integration flow or changes the same. You can also resolve if there are any errors._

### Feedback Type (Optional)

spelling or grammar

### Page Title on SAP Help Portal (prefilled)

Simulation of an Integration Flow

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/simulation-of-integration-flow

**Comment by SrutiSagaram** [comment]
Hi @michael-eaton 

Thanks for the feedback. We will check and get back to you.

**Comment by Karunaharan** [comment]
Hi @michael-eaton ,
Thanks for noticing this. We have fixed the issue. You can see the changes after our next publishing cycle.

Regards,
Karuna
