### ISSUE TITLE
Incomplete / ambigous list of supported script types

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-integration-suite#77]
### Issue description

The page states: 

"File resource is a script or code snippet that can be attached to flows using policies.

An API proxy container supports definition of a number of Java, Python, or XSL scripts."

Correct would be from my point of view: "An API proxy container supports definition of a number of JavaScript, Python, or XSL scripts."

The dropdown in the system lists:
- Javascript
- Python
- XSL
- XSD (not mentiond in the documentation)
- WSDL (not mentiond in the documentation)

As XSD and WSDL are not scripts, but schemas I would amend the first sentence to "File resources are scripts or schemas that can be attached to flows using policies."

That the item in the user interface is named "Scripts" does not really help in connecting this part of the documentation to the user interface.

Kind regards,
Sebastian

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

File Resource

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/file-resource

**Comment by Kakabira** [comment]
Hi @sebastianesch, 
We have addressed your comment. Please see: https://help.sap.com/docs/integration-suite/sap-integration-suite/file-resource
