### ISSUE TITLE
Monitor Event Mesh Page contains no content

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-integration-suite#78]
### Issue description

The page is empty.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Monitor Event Mesh

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/monitor-event-mesh

**Comment by MelanieCueppers** [comment]
Hi @sebastianesch, thank you for your feedback! We’ll look into it and come back to you if we have any questions.
