### ISSUE TITLE
Migration - Supported Patterns - Description for Recipient List Asynchronous is missing

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-integration-suite#79]
### Issue description

The section "Recipient List Asynchronous" has no text or figures.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Supported Patterns

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/supported-templates#loiob5d43f624696473b93b812cdc36277ad

**Comment by SrutiSagaram** [comment]
Hi @sebastianesch 
Thank you for your feedback. We will take a look and get back to you.

**Comment by Karunaharan** [comment]
Hi @sebastianesch - the issue is fixed now. Thanks for letting us know.
