### ISSUE TITLE
Monitoring and Troubleshooting Page is at top level of Integration Suite docs, but covers only SAP Graph

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-integration-suite#80]
### Issue description

The Page "Monitoring and Troubleshooting" is at the top level of the Integration Suite documenation and I would expect an overview over all Monitoring and Troubleshooting topics covering all Integration Suite Capabilities, but the page covers only SAP Graph.

One could get the impression that all Issues with Integration Suite should be reported for component BC-CP-IS-GRAPH. I guess this is not the intention of this documentation.

I would expect for example an overview over the different comonents in the Support Portal for Integration Suite and an explanation which Component to use for what.

Same for further monitoring and troubleshooting topics.

### Feedback Type (Optional)

content structure

### Page Title on SAP Help Portal (prefilled)

Monitoring and Trouble Shooting

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/monitoring-and-troubleshooting

**Comment by SrutiSagaram** [comment]
Hi @sebastianesch 

Thank you for the feedback. The title of this document should read Monitoring and Troubleshooting for Graph. I am checking why that is not the case.
Regarding your feedback about the topic content itself, we will definitely discuss this and get back.

**Comment by sebastianesch** [comment]
If this is only the Monitoring and Troubleshooting Guide für SAP Graph and there is a Page "Troubleshooting for Edge Integration Cell" where are the Monitoring and Troubleshooting Guides for the other Capabilities?

**Comment by SrutiSagaram** [comment]
Hi @sebastianesch 
The troubleshooting guides for most of the other capabilities can be accessed from the tenant. Click on your profile > Troubleshooting guides.

**Comment by sebastianesch** [comment]
But the documentation should cover all areas, or not? When I have to write operations documents, I don't want to link my tenants, but the SAP provided documentation, that explains the basics. If there is only partial troubleshooting information available in the documentation, it looks as if there are gaps.

**Comment by SrutiSagaram** [comment]
Hi @sebastianesch 
The troubleshooting guides are a part of the documentation - but rendered differently. If you mean you would like this to be a part of our user guide - there is a plan for this in the future.
