### ISSUE TITLE
Still Incomplete List of Role Templates for Cloud Foundry / Missing Persona Definitions

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-integration-suite#81]
### Issue description

As mentioned in issue #60 the table with the explanations of Role Templates for Cloud Foundry is still missing the following Role Templates:

- AuthGroup_Administrator
- AuthGroup_BusinessExpert
- AuthGroup_ContentPublisher
- AuthGroup_IntegrationDeveloper
- MonitoringArtifactsDeploy
- QueuesRetry

Especially for the AuthGroup_* Role Templates a description of the covered authorizations in the AuthGroup would be very valuable when developing authorization concepts and deciding if the AuthGroups can be used or not.

The Role Template WorkspacePackagesTransport has no Persona associated. That seems also like a gap in the documentation.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Tasks and Permissions for Cloud Integration

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/tasks-and-permissions-556d5575d4b0483e85d4f3251f21d0ec

**Comment by SrutiSagaram** [comment]
Hi @sebastianesch 

Thank you for your feedback, we will check and get back to you.

**Comment by pe-gu** [comment]
Hello @sebastianesch,
I have updated the documentation:
https://help.sap.com/docs/integration-suite/sap-integration-suite/tasks-and-permissions-556d5575d4b0483e85d4f3251f21d0ec

The description of role AuthGroup_ContentPublisher is missing. The reason is: This role is exclusively intended for usage by integration developers at SAP or for dedicated SAP partners. It is not intended for use beyond that.
Many thanks again for your input!

**Comment by sebastianesch** [comment]
Then maybe include that information in the documentation. The role is in the system and when an audit takes place and there is no information about what this role does, this might raise additional questions.

**Comment by pe-gu** [comment]
Hello @sebastianesch, thanks for the comment! I proceeded accordingly and updated the documentation now. You are right: Having this undocumented creates room for questions. Thanks again!
