### ISSUE TITLE
XML for Select Query

### ISSUE THREAD

**Issue by varunr87** [SAP-docs/btp-integration-suite#82]
### Issue description

XML Structure for Select Query does not include <access> tags. These should be there in the structure to allow for Clumn Selection in the Select Query. 
Should be similar to what is defined in the [SAP PI Help Documentation](https://help.sap.com/docs/SAP_NETWEAVER_750/5cf7d2de571a45cc81f91261668b7361/447b7171fde93673e10000000a114a6b.html). 

### Feedback Type (Optional)

incorrect statement

### Page Title on SAP Help Portal (prefilled)

Payload and Operation

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/payload-and-operation

**Comment by SrutiSagaram** [comment]
Hi @varunr87 
Thank you for your feedback. We will check and get back to you.

**Comment by HarshitaSuryavanshi** [comment]
Hi @varunr87 
Thanks for the feedback. We have enhanced the sample code with column selection example in Select query. 
The updated content will be visible with the next SAP help portal refresh release.

**Comment by varunr87** [comment]
72993
