### ISSUE TITLE
Archiving config was not lost even after undeployment/deployment sycle

### ISSUE THREAD

**Issue by freest5** [SAP-docs/btp-integration-suite#83]
### Issue description

Dear colleagues,
As it is described in this page, **the archiving configuration is lost, if an integration flow is undeployed. You've to reconfigure archiving after redeployment of the integration flow**.

Today I have tested the configuration of the Archiving on IFlow level in our internal SAP CI tenant.
And configuration stayed the same as before undeployment.
Have this functionality changed?

May I kindly ask you on top of that, will the archiving configuration be kept in case of re-deployment (without undeployment step, and in case of transporting the IFlow to the next tier like QA->PROD)?

Thank you in advance, Stan.

![image](https://github.com/SAP-docs/btp-integration-suite/assets/56725869/44034e2c-6635-445c-9e5e-aa22d80b74e8)

### Feedback Type (Optional)

outdated information

### Page Title on SAP Help Portal (prefilled)

Enable Archiving in the Cloud Foundry Environment

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/enable-archiving-in-cloud-foundry-environment

**Comment by SrutiSagaram** [comment]
Hi @freest5 
Thank you for your feedback, we will check and get back to you.

**Comment by pe-gu** [comment]
Hello @freest5, thanks a lot for your Feedback! This is indeed an outdated text. I have checked with the development team, and they also confirmed that the behaviour that you observed is "as designed". I corrected the documentation, and the change will be visible after the next patch (in the next few days). Thank you!
