### ISSUE TITLE
The list of supported Oracle JDBC driver is not available which can be very confusing

### ISSUE THREAD

**Issue by vinben06** [SAP-docs/btp-integration-suite#85]
### Issue description

As a SAP Support Engineer (vincent.benayoun@sap.com) I regularly get mails from customers complaining that they failed to deploy an Oracle driver on their CI tenant.
First of all the tchnical error does not give any sort of help on why the driver deployment failed.
The help.sap.com documentation does not tell customers that only a limited number of the driver is supported (ojdbc6, ojdbc7, ojdbc8). You need to search into SAP Notes to find that -> 3140854 - Unable to upload ORACLE jdbc driver due 'jdbc driver null' error
This should clearly be stated in the documentation.
Instead of pointing to the general Oracle driver page which only offers to download non supported driver versions, you should instead point to the supported ones ! That would avoid getting lost in by links that points to unusable content.
e.g. : https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc8/19.16.0.0/ojdbc8-19.16.0.0.jar

Regards
Vincent
I059819

### Feedback Type (Optional)

incorrect statement

### Page Title on SAP Help Portal (prefilled)

Configure JDBC Drivers

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/configure-jdbc-drivers

**Comment by SrutiSagaram** [comment]
Hi @vinben06 
Thank you for your feedback. We will look into it and get back to you.
