### ISSUE TITLE
Missing prerequisites for step 5 - create service binding

### ISSUE THREAD

**Issue by ChiarJR** [SAP-docs/btp-integration-suite#86]
### Issue description

Currently it is not clear what exactly is missing. If you have followed the instructions in steps 1 to 4 and met the requirements, you cannot create a service binding as described in step 5. At step 5 you will face the info message "There are no applications in this space." It sounds like some additional prerequisites are missing. I would like to ask you to double-check the needed prerequisites and add them here:
https://help.sap.com/docs/integration-suite/sap-integration-suite/initiating-event-mesh

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Configure A Message Client

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/configure-message-client

**Comment by SrutiSagaram** [comment]
Hi @ChiarJR 

Thank you for your feedback. We will take a look and get back.

**Comment by Karunaharan** [comment]
Hi @ChiarJR,
Could you please check again? There are no prerequisites for creating a service binding. I did a round of testing without spaces and applications in my BTP cockpit. Service binding creation happened as expected.

Regards,
Karuna
