### ISSUE TITLE
Role collection "AuthGroup.APIPortalRegistration" undocumented

### ISSUE THREAD

**Issue by bauer-at-work** [SAP-docs/btp-integration-suite#88]
### Issue description

Role collection "AuthGroup.APIPortalRegistration" undocumented

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

User Roles in API Management

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/roles-collections-in-api-management-draft?advPhr=AuthGroup.ContentAuthor

**Comment by Kakabira** [comment]
Hi @bauer-at-work : We have updated the "User Roles in API Management" topic (https://help.sap.com/docs/integration-suite/sap-integration-suite/roles-collections-in-api-management-draft?advPhr=AuthGroup.ContentAuthor&version=CLOUD) to include the ""AuthGroup.APIPortalRegistration" role collection. However, this role was already described in the following topic: https://help.sap.com/docs/integration-suite/sap-integration-suite/create-connection-request-for-centralized-api-business-hub-enterprise-new-design?advPhr=AuthGroup.ContentAuthor&version=CLOUD
