### ISSUE TITLE
Role collection 'Integration_Provisioner' undocumented

### ISSUE THREAD

**Issue by bauer-at-work** [SAP-docs/btp-integration-suite#89]
### Issue description

I know the role collection is mentioned multiple times in the documentation of SAP Integration Suite.
However, a clear definition of the tasks associated with that collection is missing.

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Configuring User Access to SAP Integration Suite

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_INTEGRATION_SUITE/51ab953548be4459bfe8539ecaeee98d/2c6214a3228e4b4cba207f49fda92ed4.html?locale=en-US&version=CLOUD&q=Integration_Provisioner

**Comment by SrutiSagaram** [comment]
Hi @bauer-at-work 
Thank you for your feedback. We will check and get back to you.

**Comment by SrutiSagaram** [comment]
Hi @bauer-at-work 

We've worked on this comment and added the necessary information in the same document. You will see it when the document is release next.
