### ISSUE TITLE
Typo in Point-to-Point Synchronous 

### ISSUE THREAD

**Issue by Jay-SAP** [SAP-docs/btp-integration-suite#90]
### Issue description

Typo in Point-to-Point Synchronous 

### Feedback Type (Optional)

spelling or grammar

### Page Title on SAP Help Portal (prefilled)

Supported Patterns

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/supported-templates?q=Integration%20Suite%20Migration%20Tooling#loio270776550dc34dbe97cb95403810f93f

**Comment by SrutiSagaram** [comment]
Hi @Jay-SAP 
Thank you for the feedback. We will check and get back.

**Comment by Karunaharan** [comment]
Hi @Jay-SAP,
Thanks for the feedback. The issue is fixed now and you can expect the changes in a couple of hours.
