### ISSUE TITLE
Correction for retention periods

### ISSUE THREAD

**Issue by freest5** [SAP-docs/btp-integration-suite#93]
### Issue description

Dear colleagues, could you please fix the typo and add missing details?

**Message content stored by JMS adapter:**
_Wrong:_ Can be defined by integration developer (default value: 90 days)
_Correct:_ Can be defined by integration developer (default value: **30** days**, maximum possible value is 180 days**)

**Data stored by Data Store operations step:**
_Update with maximum value:_ Can be defined by integration developer (default value: 30 days**, maximum possible value is 180 days**)

Doc for JMS:_ https://help.sap.com/docs/cloud-integration/sap-cloud-integration/configure-jms-receiver-adapter
_Doc for Write operation:_ https://help.sap.com/docs/cloud-integration/sap-cloud-integration/define-data-store-write-operations

Btw, the maximum value is also missing on the page **https://help.sap.com/docs/cloud-integration/sap-cloud-integration/configure-jms-receiver-adapter**. Only default is mentioned there. Probably you could also update it there.

Thank you in advance,
Stan.

### Feedback Type (Optional)

incorrect statement

### Page Title on SAP Help Portal (prefilled)

Specific Data Assets

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/specific-data-assets?q=90%20days

**Comment by MelanieCueppers** [comment]
Hi @freest5, thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by pe-gu** [comment]
Hi @freest5, thanks a lot for your contribution! I have updated the relevant topics accordingly.
