### ISSUE TITLE
export to Excel

### ISSUE THREAD

**Issue by alcast0007** [SAP-docs/btp-integration-suite#94]
### Issue description

 need the ability to export tables out of https://help.sap.com/docs webpages into Microsoft Excel

### Feedback Type (Optional)

other

### Page Title on SAP Help Portal (prefilled)

Tasks and Permissions

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/tasks-and-permissions?q=Role%20Collection

**Comment by MelanieCueppers** [comment]
Hi @alcast0007, thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by Karunaharan** [comment]
Hi @alcast0007 
Unfortunately, we won't be able to help you with this. SAP Integration Suite is a cloud software, we add new roles frequently. As I write this reply, we are adding new information to the page. After you download the current version, we might update the content and there is a high chance that you might miss some useful information about new roles. 
We suggest you bookmark the page and consume the "cloud" version to consume the latest version. 

Regards,
Karuna
