### ISSUE TITLE
Variables in Scripts

### ISSUE THREAD

**Issue by keshavdesai** [SAP-docs/btp-integration-suite#99]
### Issue description

Variables in Scripts
Context: In a script, empty variables that you initiated in the script and which keep large data.

Why: If you define variables in a script, the variables are kept in memory even if the processing of the script ended. The memory is kept until the entire integration process ends.

How: _Either remove particular variables from the script or purge all variables at the end of the script._

Clarity is needed regarding the removal/purge of particular variables at the end of the script please. Does it mean we assign null value to variables or clear arrays/lists/maps used and that contain large amounts of data? 

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Optimize Memory Footprint

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-integration/sap-cloud-integration/optimize-memory-footprint?version=Cloud

**Comment by pe-gu** [comment]
Hello @keshavdesai 
Many thanks for your input! I have added some information to the topic.

**Comment by pe-gu** [comment]
Many thanks for your contribution!

**Comment by keshavdesai** [comment]
Peter, thanks a ton for the reply and the update on help portal. Its clear now for binding variables. Is it expected to clear non binding (defined/typed) variables defined in the script too? Do they stay in memory until the iFlow processing is complete please?
